### ISSUE TITLE
Manage Search History with Redux

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#11]
- Save search data in redux, saved data should be an object` {search_text: x, search_type: y}`
- Change input type to a HTML5 **autocomplete**
- on choosing an old search set, **search_text** & **search_type** must be updated according to the object's key/values
- selecting an artist to open his albums list should also be saved as history. For exemple, taping **'Ra'** on search text and seach by _artist_, then you select the result **'Radiohead'** to see albums, then the result **'Rammstein'** to see their albums, will save **3** items in _Redux_: 

> 'Ra' (as a search input), 
> Radiohead & Rammstein (as consulted search result)

**Comment by aymendhaya** [comment]
Please notifiy here about done issues so i can close them.

**Comment by Naouras** [comment]
done
