### ISSUE TITLE
@Zied // AlbumComponent

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#17]
On` handleRouter()` please make changes to use `match.params` instead of `history.location.pathname`

since the call of `handleRouter()` is in an anchor, let the function return a string path and replace anchor with router **Link**

**Comment by ZiedHf** [comment]
@aymendhaya The function `handleRouter` should be as the following ?

```jsx
let path =
      this.props.match.props.search_type === 'artist'
        ? '/search/artist/' +
          this.props.match.params.search_text +
          '/' +
          this.props.match.params.art_id +
          '/' +
          album_id
        : '/search/album/' + this.props.match.params.search_text + '/' + album_id;

    this.props.history.push(path);
```

Then I replace the <a href> with <Link> ?

**Comment by aymendhaya** [comment]
yes but without `this.props.history.push(path)`. instead it willm be return path then on your `<a` tag, replace a with `Link`, and replace `onClick` with `to={this.handleRouter()}`

**Comment by ZiedHf** [comment]
@aymendhaya I need to specify the `id` of panel also in the `href` parameters, this is why I thought that I need just to add the handleRouter in `onclick` and change it using `history.push()` :
```jsx
<a
              data-toggle="collapse"
              aria-expanded={aria_expanded}
              **href={'#tabpanel-' + album.id.toString()}**
              onClick={e => this.handleRouter(album.id)}
              aria-controls={'tabpanel-' + album.id.toString()}
            >```

**Comment by aymendhaya** [comment]
@ZiedHf  the accordion handler is related to `aria-controls` not to `href`. you dont need `href` to open the accordion. try **Link** with `aria-controls` directive/prop and it will works fine

**Comment by ZiedHf** [comment]
@aymendhaya won't work at all without the the `id` into `href` ..
[Example](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_collapsible2&stacked=h)

**Comment by ZiedHf** [comment]
Unfortunately I didn't find anyway to just ignore the `href` into the collapse element and replace it by the function.
I find two thing they may solve my problem I want to check this with you @aymendhaya, please correct me if I miss something or there is a better way :

- the `<Link>` tag calls by default the `history.push`. So maybe it's okay to add the function into onClick function and handle the link by `push` function.
- The essential problem for me was passing `path` as `string` like `push("root/var1/var2")` don't preserve my attributes in the link so I was treating them a sample text by using `location`. This was a problem.
I find this structure in the `history` documentation, by using this I preserve all the attributes and I can use Route in the right way without `location` : 
```jsx
this.props.history.push({
        pathname: path,
        search_text: this.props.match.params.search_text,
        search_type: this.props.match.params.search_type,
        art_id: this.props.match.params.art_id,
        alb_id: album_id
      });
```

**Comment by aymendhaya** [comment]
I prefer to let it work with **Link**, all requests and issues that i am making to you on **github** are written for your own benefits to help you being familiar with the policies of development in the **smartlis_ui_components** project, not to to finish **Smartify**. So your suggestion is to make it work, since we are not pressed we will make it work as it should be universally or for our upcoming projects. Automatically, if you have an `a tag` with `onClick `to call `push`, it's a **Link** case. i did comment here the `href `and it still work perfectly, the only difference is that the album name on blur dont get blue and underlined. all the rest is working fine. 
> Try to find the tip on it even if it demands that you change your accordion policy to fit using Link, not the opposite

**Comment by ZiedHf** [comment]
@aymendhaya Obviously this wasn't my day, I was stuck in some basic stuff like `data-target` in bootstrap.
I think my last commit contains the core of your idea. Please check it out.

**Comment by aymendhaya** [comment]
the 'to' prop should contain the route, the same string that you usually sent through `push()`, so we want to remove `onClick()` `and push()` 

I am still sure that href have nothing to do on your code.

Check this exemple on how collapsing works on bootstrap
https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_collapsible&stacked=h

**replace:**

`<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">Simple collapsible</button>
`
**with:**

`<a data-toggle="collapse" data-target="#demo">Simple collapsible</a>
`

> you will notice that data-target handle the collapsing by calling the id of the div. you can replace your code with this exemple
