### ISSUE TITLE
@Naoures: issue on saving search history

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#21]
- You are only saving search words, consulted result also should be saved on redux.
- Duplicated search_text/search_type should be avoided on redux, we only save search criterias once.

> If you search for 'david' then you open 'david gilmoure' and 'david bowie' results, you shoud have on search history 3 values: **'david', 'david bowie' & 'david gilmoure'**

**Comment by Naouras** [comment]
done
