### ISSUE TITLE
Multiline setState() / Dynamize button disabler / Remove useless functions 

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#3]
# 1- Avoid multiline setState( ... ) :

> ```
>       this.setState({search_type: e.target.value})
>       this.setState({search_result: undefined})
>       this.setState({search:false})
> ```

**is better to call the function once with all the items to edit in one single object:**

> `  this.setState({search_type: e.target.value, search_result: undefined, search:false})
`
# 2- You don't need _disable_search_ on state:

> ```
> <button onClick={this.search} className="btn btn-primary" disabled={this.state.disable_search}>Search</button>
> ```

**can simply be :**
> ```
> <button onClick={this.search} className="btn btn-primary" disabled={!this.state.search_text}>Search</button>
> ```
**{!this.state.search_text} will return true if this.state.search_text is null, undefined or an empty string**

# 3- Functions for handling input and select changes are now useless:

**So now, you can only call setState({ ... }) on onChange=" ... "**

**Comment by ZiedHf** [comment]
1- Avoid multiline setState( ... ) : 
Done :) I checked out all the components.

2- You don't need disable_search on state : 
The disable state that I wrote depends only on search_text, I forget to add search_type too.
```
disabled={!this.state.search_text || !this.state.search_type}
```
3- Functions for handling input and select changes are now useless : 
Done.
