### ISSUE TITLE
@SearchResultComponent

### ISSUE THREAD

**Issue by aymendhaya** [aymendhaya/react-smartify#5]
1- Function `doSearch()` should be moved to child components. 
2- **SearchResultComponent** should be as a Container Component. It will only contain 3 routes and only one will be rendered according to search_type. no functions needed and no operations.
3- Calling the components on the `<Route .... `should be with the prop/directive` Component=...` and not `render= ...` No props should be sent through the component call

**Comment by ZiedHf** [comment]
@aymendhaya The three component Artist, Album and track will contains the whole list ?
I thought that Artist without 's' is a component of one artist. Should I add three other component contain the result like : 
- ArtistListComponent
- AlbumListComponent
- TrackListComponent
So I can call Artist component as only one Artist from FavoriteComponent and display the list from there.

**Comment by aymendhaya** [comment]
@ZiedHf we don't need to add ArtistListComponent but the ArtistComponent will behave like an ArtistListComponent for now. you render all the artists/albums/tacks into their respective components. our main purpose is to have propless components call. Or if you want to keep ArtistComponent as a single element, declare an internal component to display the list without externalize it on a seperate js file. We keep on working on the first option for the moment.
